server: 
  port: 8001
spring: 
  application:  
    name: position-cty #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/position?characterEncoding=UTF8&useSSL=false
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  mail:
    host: 220.181.12.13
    username: caotiyuan@163.com
    password: DZCDISXQEFZYEUXP
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    port: 465
    protocol: smtp
    default-encoding: UTF-8
  redis:
    database: 0
    host: 124.221.104.172
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 -1 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: ''
    port: 6379
minio:
  endpoint: http://124.221.104.172:9001
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: position