spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
minio:
  endpoint: http://124.221.104.172:9001
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: position