erupt:
  # 是否开启csrf防御
  csrfInspect: true
  # 开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置（同 Spring Boot）
  redisSession: true
  # redis session是否自动续期，1.10.8及以上版本支持
  redisSessionRefresh: false
  # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  uploadPath: D:/erupt/pictures
  # 是否保留上传文件原始名称
  keepUploadFileName: false
  # 项目初始化方式，默认值 file，1.10.10及以上版本支持，可选值：
  # NONE  不执行初始化代码
  # EVERY 每次启动都进行初始化
  # FILE  通过标识文件判断是否需要初始化
  initMethodEnum: file
  upms:
    # 登录session时长（redisSession为true时有效）
    expireTimeByLogin: 60
    # 严格的角色菜单策略，如果非管理员用户拥有“角色管理权限”则仅能编辑已有权限的角色菜单
    # 1.10.6 及以上版本支持
    strictRoleMenuLegal: true
  # 是否开启任务调度（导入erupt-job时有效）
  job.enable: true
  # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
  security.recordOperateLog: true
server:
  port: 8001
spring:
  application:
    name: position-cty #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/position?characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  hibernate:
    ddl-auto: update
  mail:
    host: 220.181.12.13
    username: caotiyuan@163.com
    password: DZCDISXQEFZYEUXP
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    port: 465
    protocol: smtp
    default-encoding: UTF-8
  redis:
    database: 0
    host: 124.221.104.172
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 -1 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: ''
    port: 6379
minio:
  endpoint: http://124.221.104.172:9001
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: position
erupt-app:
  # 登录失败几次出现验证码，值为0时表示一直需要登录验证码
  verifyCodeCount: 2
  # 登录密码是否加密传输，特殊场景如：LDAP登录可关闭该功能获取密码明文
  pwdTransferEncrypt: true
  # 多语言配置，默认支持：简体中文、繁体中文、英文、日文；具体配置详见erupt-i18n模块
  locales: [ "zh-CN","zh-TW","en-US","ja-JP"]
  # 自定义登录页路径，1.10.6 及以上版本支持
  loginPagePath:
